on:
  push:
    # toda vez que eu criar qualquer tag
    tags: ["*"]

jobs:
  release:
    # só vai executar o job release se o github.ref começar com refs/tags/v
    if: startsWith(github.ref, 'refs/tags/v')
    # a estratégia de matrix do github permite que eu faça uma execução em
    # paralelo, da github action em vários ambientes diferentes
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # checkout é para baixar o código na sua versão mais atualizada
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: apt-update
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update

      - name: autoremove
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install libarchive-tools rpm

      - name: Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
